### ISSUE TITLE
Error Creating Order

### ISSUE THREAD

**Issue by tomasmb** [cryptomkt/cryptomkt-go#2]
Hi, I have been experiencing an error when trying to create an order with the following method:

```javascript
order, err := c.Client.CreateOrder(
    args.Amount(fmt.Sprintf("%f", amount)),
    args.Market(market),
    args.Price(fmt.Sprintf("%f", price)),
    args.Type(c.OperationType))

if err != nil {
    log.WithFields(log.Fields{
	"operationId":       c.OperationId,
	"operationName":     c.OperationName,
	"botType":           c.OperationType,
	"operationCurrency": c.Currency,
    }).WithError(err).Error("Error creating order")
    return 0
}
```

The strange thing is that the order is created with no problem a few times and suddenly it stops working. I cant know what the problem is, as the error caught in "err" is empty. This makes it impossible for me to debug this specific error.

Thank you

**Comment by Insmael** [comment]
Hi, thanks for the notification, The current sdk makes use of another source code so the problem is no longer a problem.
