### ISSUE TITLE
wrong assignation bids to asks

### ISSUE THREAD

**Issue by celsogg** [cryptomkt/cryptomkt-go#9]
Hi, in [this line](https://github.com/cryptomkt/cryptomkt-go/blob/545198fb24efddb2291362710a9b3d184dc00aca/models/convertions.go#L13) there is an error, asks are being appended to the bids array.

**Comment by ppbustamante** [comment]
@celsogg Fixed in https://github.com/cryptomkt/cryptomkt-go/releases/tag/v3.1.1

Thank you for reporting
